org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.projectcachedir=D:/Programs/Android/sdk/gradle-temp/project-cache/Skylarkin

# Keep Kotlin persistent data out of the project workspace.
kotlin.project.persistent.dir=D:/Programs/Android/sdk/gradle-temp/kotlin-project/Skylarkin
kotlin.project.persistent.dir.gradle.disableWrite=true
